import Link from "next/link";
import "./global.css";
import { Metadata } from "next";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// pembahasan ini ada di r10, pelajari dulu dari r1 - r9
export const metadata: Metadata = {
  title: {
    absolute: "", // menimpa semua value yang lain
    default: "nextjs", // default untuk child
    template: "%s | dinamis", // nilai dinamis tergantung childnya
  },
  description: "Generated by Next.js",
};

const homeMenus = [
  { href: "/", text: "home" },
  { href: "/r1", text: "r1" },
  { href: "/r2", text: "r2" },
  { href: "/r3", text: "r3" },
  { href: "/r4/r4all", text: "r4" },
  { href: "/r5", text: "r5" },
  { href: "/r6", text: "r6" },
  { href: "/r7login", text: "r7login" },
  { href: "/r7register", text: "r7register" },
  { href: "/r7forgotpass", text: "r7forgotpass" },
  { href: "/r8a", text: "r8a" },
  { href: "/r8b", text: "r8b" },
  { href: "/r9", text: "r9" },
  { href: "/r10", text: "r10" },
  { href: "/r11", text: "r11" },
  { href: "/r12", text: "r12" },
  { href: "/r13", text: "r13" },
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="h-16 border-b w-full px-3 lg:px-12">
          <nav className="h-full flex gap-8 items-center ">
            <div>Logo</div>
            <div className="flex gap-4 overflow-x-scroll">
              {homeMenus.map((menu, i) => (
                <Link key={i} href={menu.href}>
                  {menu.text}
                </Link>
              ))}
            </div>
          </nav>
        </header>
        <main className="px-3 lg:px-12">{children}</main>
      </body>
    </html>
  );
}
