import "./global.css";
import Footer from "@/components/footer";
import { Header } from "@/components/header";
import { Providers } from "./providers";
import Main from "@/components/main";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`flex flex-col min-h-screen dark:bg-slate-800`}>
        <Providers>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
