import "./global.css";
import { Metadata } from "next";
import Footer from "@/components/footer";
import { Header } from "@/components/header";
import { Providers } from "./providers";
import Main from "@/components/main";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// pembahasan ini ada di r10, pelajari dulu dari r1 - r9
export const metadata: Metadata = {
  title: {
    absolute: "", // menimpa semua value yang lain
    default: "nextjs", // default untuk child
    template: "%s | dinamis", // nilai dinamis tergantung childnya
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`flex flex-col min-h-screen dark:bg-slate-800`}>
        <Providers>
          <Header />
          <Main>{children}</Main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
